Config = {}
Config.Framework = "RSG" -- RSG

Config.GiveAnimation = true
Config.Tasks = {
    'Mondd, hogy szeretsz, 5 különböző nyelven.',
    'Ismételj meg valamit, amit az első beszélgetésünk során mondtál.',
    'Meséld el a legédesebb pillanatot, amikor velem voltál.',
    'Mondd, hogy szeretsz.',
    'Emlékezz vissza és meséld el a legviccesebb helyet, ahol együtt jártunk.',
    'Énekeld el a kedvenc dalunkat, és mondd: "Ez a mi dalunk!"',
    'Adj nekem egy becenevet, és magyarázd el, miért ezt választottad.',
    'Mondd ki hangosan, hogy szeretsz.',
    'Idézd fel és mondd el, miről beszélgettünk az első randinkon.',
    'Meséld el a legviccesebb emléket, amin együtt nevettünk.',
    'Milyen színű ruha volt rajtam az első randinkon? Mondd el.',
    'Melyik tulajdonságomat szereted a legjobban? Mondd el.',
    'Mondd ki újra, hogy szeretsz.',
    'Mondd el a kedvenc desszertünket, és mondd: "Ezt együtt kell megennünk!"',
    'Mondj el valami különlegeset a mai napodról hangosan.',
    'Meséld el, mit szeretsz velem a legjobban csinálni.',
    'Mondd el a kedvenc filmszereplőnket, és mondd: "Ő minket képvisel!"',
    'Mondd el hangosan, mit gondoltál rólam, amikor először megláttál.',
    'Meséld el a legviccesebb közös emlékünket.',
    'Melyik időszakban szerettél engem a legjobban? Mondd el.',
    'Énekelj egy dalt, amely kifejezi, mennyire szeretsz.',
    'Mondd el a legjobb sorozatot, amit együtt néztünk.',
    'Mikor gondolsz rám a legtöbbet? Mondd el.',
    'Hogyan emlékszel rám a legjobban? Mondd el.',
    'Melyik időszakban mosolyogtattalak meg a legjobban? Mondd el.',
    'Mesélj valamiről, amit együtt tervezünk csinálni.',
    'Hogyan szólítottál meg, amikor először találkoztunk? Mondd el.',
    'Milyen íz tesz engem a legboldogabbá? Mondd el.',
    'Mondd ki a legédesebb üzenetet, amit nekem írhatnál, hangosan.',
    'Mikor voltál rám a legféltékenyebb? Mondd el.',
    'Utánozz engem a legviccesebb módon.',
    'Mi volt az első film, amit együtt néztünk? Mondd el.',
    'Olvass fel egy verset, amely kifejezi, mennyire szeretsz.',
    'Mi volt az első kedves dolog, amit nekem mondtál? Mondd el.',
    'Mesélj egy emléket, amely boldoggá tett engem.',
    'Mi járt a fejedben, amikor először találkoztunk? Mondd el.',
    'Melyik cselekedetem hatott rád a legjobban? Mondd el.',
    'Mesélj a legromantikusabb pillanatunkról.',
    'Hogyan érezted magad, amikor először megcsókoltál? Mondd el.',
    'Hogyan utánozol engem a leggyakrabban? Mondd el.',
    'Hogyan szeretsz engem a legjobban? Mondd el.',
    'Melyik helyet szeretnéd velem a legjobban meglátogatni? Mondd el.',
    'Mondd el a legrövidebb szerelmes üzenetet, amit nekem küldenél.',
    'Miről beszélgettünk, amikor először találkoztunk? Mondd el.',
    'Mondd el a kedvenc közös ünnepi tevékenységünket.',
    'Melyik helyen szeretsz engem a legjobban? Mondd el.',
    'Egy szóval írd le azt a pillanatot, amikor először megcsókoltál.',
    'Melyik dal emlékeztet rám a legjobban? Mondd el.',
    'Mondj egy mondatot, amely kifejezi a szerelmedet irántam.',
    'Egy mondatban írd le azt a pillanatot, amikor belém szerettél.'
}
