Config = {}
Config.Framework = "VORP" -- RSG

Config.GiveAnimation = true
Config.Tasks = {
    'Say you love me in 5 different languages.',
    'Repeat something you said in our first conversation.',
    'Tell me the sweetest moment when you were with me.',
    'Say you love me.',
    'Remember and tell the funniest place we went together.',
    'Sing our favorite song and add, "This is our song!"',
    'Give me a nickname and explain why.',
    'Say you love me out loud.',
    'Recall and tell me what we talked about on our first date.',
    'Tell me the funniest memory that made me laugh.',
    'What color was I wearing on our first date? Tell me.',
    'What feature of mine do you love the most? Tell me.',
    'Say you love me again.',
    'Tell me our favorite dessert and say, "We should eat this together!"',
    'Explain something special to you today out loud.',
    'Tell me what you love doing with me the most.',
    'Tell me our favorite movie character and say, "It represents us!"',
    'Tell me what you thought when you first saw me, out loud.',
    'Tell me our funniest memory.',
    'In which time period do you love me the most? Tell me.',
    'Sing a song that represents how much you love me.',
    'Tell me the best series we watched together.',
    'Tell me when you think about me the most.',
    'Tell me how you remember me the most.',
    'Tell me which time period you make me smile the most.',
    'Tell me something we plan to do together.',
    'How did you address me when we first met? Tell me.',
    'What flavor makes me the happiest? Tell me.',
    'Say the sweetest message you could write to me, out loud.',
    'When were you most jealous of me? Tell me.',
    'Imitate me in the funniest way.',
    'What was the first movie we watched together? Tell me.',
    'Read a poem that tells how you love me.',
    'What was the first sweet thing you said to me? Tell me.',
    'Tell me a memory that made me happy.',
    'What was on your mind when you first met me? Tell me.',
    'Which action of mine impressed you the most? Tell me.',
    'Tell me about our most romantic moment.',
    'How did you feel when you first kissed me? Tell me.',
    'How do you imitate me the most? Tell me.',
    'How do you love me the most? Tell me.',
    'Which place do you want to visit the most together? Tell me.',
    'Tell me the shortest love message you could send to me.',
    'What did we talk about when we first met? Tell me.',
    'Tell me our favorite holiday activity.',
    'In which place do you love me the most? Tell me.',
    'Describe the moment when you first kissed me in one word.',
    'What song reminds you of me the most? Tell me.',
    'Say a phrase that expresses your love for me.',
    'Describe the moment you loved me in one sentence.'
}